### PR TITLE
Fix unresponsive zoom behavior

### LINKED ISSUE #45: Unresponsive zoom
When scrolling or clicking zoom controls, the map zooms in or out an itty bit at a time. Should behave more like ipyleaflet, JupyterGIS, leafmap, folium, etc.

### PR DESCRIPTION
**Pull request by nakul-py**
The zoom bug is because of `change:resolution` fires many times during a zoom animation, including tiny intermediate values. So `zoomChanged` code runs so we get a loop like When we click zoom-in, OL starts smooth zoom animation but intermediate zoom values get synced to Python than synced value comes back that's why `setZoom()` is called again with a partial value and animation keeps getting interrupted / flattened.

https://github.com/user-attachments/assets/73fb7e50-6f69-4888-ad5e-4d4a5f4bf811

- Closes #45

### CODE REVIEW

File: src/widget.ts [hunk 1]
```diff
@@ -127,18 +125,21 @@ export class MapView extends DOMWidgetView {
       this.handleMapClick(event);
     });
 
-    this.map.getView().on('change:center', () => {
-      this.model.set('center', this.map.getView().getCenter());
+    this.map.on('moveend', () => {
```
Comment (mfisher87) [inline src/widget.ts:128]: This is nice :)

**Review by mfisher87 — COMMENTED** [review]
This seems good! Thanks! But I'd like a bit more context in this PR for posterity. What was the root cause of this behavior?

**Review by mfisher87 — APPROVED** [review]

**Comment by mfisher87** [comment]
Nice work, thank you!
